export const UPDATE_O_AUTH_TOKEN = "UPDATE_O_AUTH_TOKEN";
export const UPDATE_USER_ID = "UPDATE_USER_ID";
export const LOG_OUT = "LOG_OUT";
export const PLAYLIST_SONGS_CHOSEN = "PLAYLIST_SONGS_CHOSEN";
export const PLAYLIST_OPTIONS_CHOSEN = "PLAYLIST_OPTIONS_CHOSEN";
export const UPDATE_PLAYLIST_ID = "UPDATE_PLAYLIST_ID";
export const UPDATE_RECOMMENDATIONS = "UPDATE_RECOMMENDATIONS";
